apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskdemo
spec:
  selector:
    matchLabels:
      app: flaskdemo
  replicas: 2
  template:
    metadata:
      labels:
        app: flaskdemo
    spec:
      containers:
      - name: flaskdemo
        image: snehalatabarenkal/python-app:latest1
        imagePullPolicy: Always
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  selector:
    app: flaskdemo
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
  type: LoadBalancer